### ISSUE TITLE
Ability to store values in ESC via a Pulumi programs

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/esc#137]
Use case:

I am setting up what I call "delivery" roles with Pulumi in AWS that creates an OIDC role.

I want to be able to reference that role programmatically, but I _also_ want to store the name of that role in ESC in the relevant environment with a Pulumi provider.

**Comment by cleverguy25** [comment]
This is on the roadmap

**Comment by pierskarsenbarg** [comment]
Will this work with any resource that can be created through Pulumi?

Use case: I create a load of secrets in AWS Secrets Manager and I want them to be available through ESC

**Comment by komalali** [comment]
Related: https://github.com/pulumi/pulumi-pulumiservice/issues/225

**Comment by dbeattie71** [comment]
What would be the difference between this feature and creating stack outputs then using a pulumi-stacks provider?

**Comment by muhlba91** [comment]
is there any information on the timeline for this?

in my case i‘m creating secrets via a pulumi program which i need to mount into kubernetes pods. on kubernetes apps are deployed via flux and i use the external-secrets operator.

it would be extremely beneficial if i can store secrets into ESC in this pulumi program and support mounting through the already existing integration of ESC into the external-secrets operator.

currently, i need to revert back using another solution to handle these secrets but such an integration would make the management way easier and streamlined.

**Comment by gunzy83** [comment]
> What would be the difference between this feature and creating stack outputs then using the pulumi-stacks provider?

I wondered the same thing.

**Comment by gunzy83** [comment]
My current use case is a project that manages Auth0 global tenant settings, including connections from our Okta IdP (including credentials for the Okta API). Using ESC's environment variables, it is possible to prevent the API credentials from ending up in state, but there are other client credentials and secrets produced that do end up in state and need to have restricted access while others are fine to be on outputs but really need to be passed via an ESC environment assigned to the platform team to configure clients and API configurations downstream.

**Comment by arunkumar611** [comment]
We shipped this recently

Launch Blogpost: https://www.pulumi.com/blog/esc-automation-api-pulumi-service-provider-launch/
Documentation: 
1. https://www.pulumi.com/registry/packages/pulumiservice/api-docs/environment/
2. https://www.pulumi.com/registry/packages/pulumiservice/api-docs/environmentversiontag/
3. https://www.pulumi.com/registry/packages/pulumiservice/api-docs/teamenvironmentpermission/
