### ISSUE TITLE
Allow setting default provider config from ESC

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/esc#138]
One of the primary sources of pain in pulumi is the copying of provider configuration values to multiple stacks. As an example, I currently have to set the following parameters in almost every one of my AWS stacks:

```
config:
  aws:region: us-west-2
  aws:allowedAccountIds:
  - <the account ID for a given environment>
```

Unless I'm mistaken, in order to leverage ESC here, I'd need to create an explicit provider for these values, or use `esc run` with environment variables.

What I'd love to be able to do is set these values in an ESC environment, and then import the environment into Pulumi, and have them be usable by the _default_ provider. If there's already a way to do that, happy to close this out

**Comment by cleverguy25** [comment]
@pgavlin I am not sure the right answer here, but I thought this was covered?

**Comment by pgavlin** [comment]
You should be able to do this using the IaC integration. In your environment definition, add the provider config to the top-level `pulumiConfig` property:

```
values:
  pulumiConfig:
    aws:region: us-west-2
    aws:allowedAccountIds:
    - <the account ID for a given environment>
```

With that done, `pulumi up` et. al. should pick up the config values for any stack that imports the environment.

**Comment by cleverguy25** [comment]
This is what I thought, the provider talk is what confused me.  @jaxxstorm Why did you think you had to create an explicit provider?

**Comment by jaxxstorm** [comment]
How would I define this in ESC and then in `pulumiConfig` ? i must have made a mistake when trying this earlier

**Comment by pgavlin** [comment]
> How would I define this in ESC and then in `pulumiConfig` ? i must have made a mistake when trying this earlier

Can you elaborate here? Anything that's in the `pulumiConfig` property of an environment will be published as stack config when consumed from Pulumi. So if I wanted to set the `aws:region` config key from an environment named `us-west-2` I might do the following:

## environment definition

```yaml
values:
  pulumiConfig:
    aws:region: us-west-2
```

## stack config

```yaml
environments:
- us-west-2
```

When running `pulumi up`/`pulumi pre`/etc., this will set the `aws:region` config key to `us-west-2`.

**Comment by jaxxstorm** [comment]
I'll give this a try tomorrow and close it out, looks like it might have been a misconfiguration on my end.

**Comment by jaxxstorm** [comment]
Okay yep, I'm an idiot. Closing!
