### ISSUE TITLE
Add an API that allows me to select the config values I return

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/esc#139]
This likely needs moving to the service repo, but opening here for now

Currently, when I open an environment via the API, I get the full JSON for that given environment returned.

This leaves it up to the client to extract the information from it that's required.

Having an API endpoint that allows me to retrieve _just_ that value would be nice

**Comment by cleverguy25** [comment]
Open already supports returning a single property path, is that not sufficient?

**Comment by cleverguy25** [comment]
The open command supports retrieving a single property path, is that not what you want?

Open the environment with the given name and return the result

This command opens the environment with the given name. The result is written to
stdout as JSON. If a property path is specified, only retrieves that property.

Usage:
  esc open [<org-name>/]<environment-name> [property path] [flags]
