### ISSUE TITLE
Add support for Vault Enterprise `namespace`s

### ISSUE THREAD

**Issue by lukehoban** [pulumi/esc#142]
The current `vault-login` and `vault-secrets` providers do not support Vault namespaces, which are necessary when wising Vault Enterprise. 

The schema for both should be expanded to support optionally specifying a namespace (for the JWT auth method to use and/or the secret to read).

**Comment by abezard-conduit** [comment]
Side note: if you use vault enterprise on-prem you can still potentially work around this issue as you have access to the root namespace. You can therefore create the vault jwt authentication method at the root namespace level and things should work.

But users of vault HCP won't have that possibility unfortunately.

**Comment by pgavlin** [comment]
> The schema for both should be expanded to support optionally specifying a namespace (for the JWT auth method to use and/or the secret to read).

This is something I wasn't sure about. Do we need both of these fields? Or is just one sufficient? Is there any relationship between the namespace for auth and the namespace(s) for secrets?

**Comment by abezard-conduit** [comment]
@pgavlin https://developer.hashicorp.com/vault/docs/enterprise/namespaces

```
When you create a namespace, you establish an isolated environment with separate login paths that functions as a mini-Vault instance within your Vault installation. Users can then create and manage their sensitive data within the confines of that namespace, including:

    secret engines
    authentication methods
    ACL, EGP, and RGP policies
    password policies
    entities
    identity groups
    tokens
 ```
 
 I think there's one exception to this which is the root namespace (which is what people on vault OSS use/have access to)

**Comment by cleverguy25** [comment]
@arunkumar611 to setup environment for testing.
