### ISSUE TITLE
Provide visibility into changes made to environments

### ISSUE THREAD

**Issue by kujenga** [pulumi/esc#190]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

The idea for this issue is to provide a way for to see the change history for environments, as well as attribution for who made the changes. Presently, the current state of an environment is all that is available. The primary motivation I have in mind for this is around debugging or investigating issues or unexpected configuration changes, as well as in general auditing of the change history to an environment.

This might be considered a pre-cursor or building block for the functionality for versioning environments outlined in https://github.com/pulumi/esc/issues/59

### Affected area/feature

Pulumi Environments

**Comment by cleverguy25** [comment]
Thanks for this issue.  This is certainly top of mind.  We have multiple plans in progress to address, this.  Versioning is one aspect, as you mentioned above.  But we plan for full auditing support, to see what changed and who changed it, as well as who is using the environment as well. We do not have concrete timelines yet but expect an update soon.

**Comment by arunkumar611** [comment]
We just shipped this as part of ESC Versioning. 

Launch blog post:https://www.pulumi.com/blog/esc-versioning-launch/
