### ISSUE TITLE
OIDC support

### ISSUE THREAD

**Issue by jtmarmon** [pulumi/esc#198]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
I want to use my ESC environments in Github actions CI pipelines. Right now I believe my only option is to create an access token that's long lived and has more access than it needs. I would rather use OIDC with Github actions for that particular ESC environment.

**Comment by jtmarmon** [comment]
Without this it feels like the promise of ESC's OIDC support (I mean with external services like AWS) is somewhat moot, since you're just exchanging one long lived credential for another

**Comment by cleverguy25** [comment]
This is on the roadmap and is one of our core priorities.  We hope to tackle this soon.

**Comment by arunkumar611** [comment]
We launched this feature recently. Here are the docs: https://www.pulumi.com/docs/pulumi-cloud/oidc/client/
