### ISSUE TITLE
Environment contents disappear from the UI

### ISSUE THREAD

**Issue by cnunciato** [pulumi/esc#216]
The ESC editor seems to be hiding the contents of an environment on view and on Save. This appears to affect only the display of the environment (the contents aren't actually removed when this happens) -- however when Save or Open is clicked in this state, the environment contents actually _are_ removed.

Steps to reproduce:

1. Create a new environment.
2. Immediately click Save on the new environment. See that the contents disappear from the UI.
3. Verify with the CLI that the contents are still there.
4. Click Open. See that the contents are empty.
5. Verify with the CLI that the contents have been deleted.

https://github.com/pulumi/esc/assets/274700/f19500b1-d3d0-448c-a290-115a51149097

**Comment by pgavlin** [comment]
okay--so the delete on `Open` happens b/c we save prior to the `Open`. I have _no clue_ why the contents are disappearing after `Save`, though.
