### ISSUE TITLE
Add docs for Environments access controls

### ISSUE THREAD

**Issue by desteves** [pulumi/esc#286]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

As a Pulumi ESC user, I'd like to learn how to limit access to the various ESC Environments defined within a Pulumi Org. Currently, [this page](https://www.pulumi.com/docs/pulumi-cloud/access-management/access-tokens/#access-token-permissions) does not cover Environments. I also looked at [this docs page](https://www.pulumi.com/docs/pulumi-cloud/access-management/teams/#team-permissions), but that's also missing any reference to Environments.

While I can navigate directly into my Pulumi Cloud account to figure it out, it requires already signing up for an account.

### Affected area/feature

Pulumi ESC. One suggestion is to add sections to the aforementioned docs pages to cover Environments access controls.

**Comment by arunkumar611** [comment]
Hi @desteves  - Can you this out? https://www.pulumi.com/docs/esc/environments/#setting-up-access-to-environments

**Comment by desteves** [comment]
Thanks, @arunkumar611. That covers the information I was looking for! Maybe we can add a link from the pages I linked to the one you linked?

**Comment by arunkumar611** [comment]
Makes sense. Created an issue to track: https://github.com/pulumi/pulumi-hugo/issues/4219
