### ISSUE TITLE
Application-level SDK for Java

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/esc#315]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Since https://github.com/pulumi/esc/issues/60, is tracking SDKs for Typescript, Python, Go, .NET, but not Java,
this issue is being opened to track the Java support.

**Comment by seanyeh** [comment]
dupe of https://github.com/pulumi/esc-sdk/issues/23
