### ISSUE TITLE
[docs] Document how an `import` may use a tag

### ISSUE THREAD

**Issue by aureq** [pulumi/esc#361]
### What happened?

When reading the [ESC reference](https://www.pulumi.com/docs/esc/reference/) page, it's not clear to the user they can actually import a separate environment with a specific tag.

The doc reads
```yaml
imports:
  - environment-a
  - environment-b
```

But this would be more useful (as an example)
```yaml
imports:
  - environment-a
  - environment-b:prod
```

Also, is it possible to import a specific revision using `@X` where `X` is a revision number?

### Example

n/a

### Output of `pulumi about`

n/a

### Additional context

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by arunkumar611** [comment]
Closing this as we plan to reorganize the docs page!

**Comment by seanyeh** [comment]
looks like arun meant to close this ticket but didn't have the right label
