### ISSUE TITLE
[docs] Inconsistent doc with Pulumi Cloud UI

### ISSUE THREAD

**Issue by aureq** [pulumi/esc#362]
### What happened?

When reading the [ESC environment](https://www.pulumi.com/docs/esc/environments/#tagging-versions) documentation for the version tagging, the `@` sign is used to separate the env name and its tag. However, going in the Pulumi Console, when copy/paste'ing the actual tag reference, the `:` character is used instead.

### Example

n/a

### Output of `pulumi about`

n/a

### Additional context

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by aureq** [comment]
@arunkumar611 I also noticed the CLI uses `@` and supports `:` but it's not mentioned ([doc](https://www.pulumi.com/docs/esc-cli/commands/esc_env_version_tag/)).

```bash
esc env version tag menfin/github-access-keys@prod
```

```bash
esc env version tag menfin/github-access-keys:prod
```

**Comment by seanyeh** [comment]
@aureq are we good to close out this issue? We now consistently use `@`
