### ISSUE TITLE
`esc login` failing if you aren't already logged in with the Pulumi CLI

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/esc#400]
### What happened?

In the docs for `esc login` ([see here](https://www.pulumi.com/docs/esc/cli/commands/esc_login/)) it says the following:

![Image](https://github.com/user-attachments/assets/3ee3abb5-73f6-455e-9237-a34f82e08bdb)

but if you login without being logged in to Pulumi Cloud first it gives the following error message:

```
❯ esc login
Error: could not determine current cloud: account 'https://api.pulumi.com' not found.Please re-run `esc login` to reset your credentials file.
```

If i _do_ re-run `esc login` as suggested I get the same error message.

### Example

1. Delete `~/.pulumi/credentials.json`
2. Run `esc login`

### Output of `pulumi about`

```
❯ esc version
v0.10.0
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by pierskarsenbarg** [comment]
If I run `esc login https://api.pulumi.com` then that works, but a) it's not what the docs say and b) I wouldn't expect someone who is brand new to ESC or Pulumi to know this

**Comment by pierskarsenbarg** [comment]
If I'm logged into a self-managed backend and run `esc login` I get the same message as well

**Comment by seanyeh** [comment]
@pierskarsenbarg I'm not able to reproduce this when I delete `~/.pulumi/credentials.json`, but I can reproduce when my `~/.pulumi/credentials.json` is empty or invalid. We could make `esc` behave similarly to `pulumi` CLI, which will overwrite the creds file if it is empty (see [here](https://github.com/pulumi/pulumi/blob/a0ad0ad243447ae97c54cf49223665cfb6d40361/sdk/go/common/workspace/creds.go#L177-L183)). In the case of the file being invalid, this issue exists in both `esc` and `pulumi`.

**Comment by pierskarsenbarg** [comment]
I'm unable to reproduce this anymore so closing this issue. Not sure why I was seeing that error yesterday.

**Comment by seanyeh** [comment]
this was closed in favor of https://github.com/pulumi/esc/issues/401
