### ISSUE TITLE
GitHub releases for ESC are empty and don't show a summary of thre changes introduced

### ISSUE THREAD

**Issue by aureq** [pulumi/esc#409]
### What happened?

Hi,

I noticed the content for each GitHub release is empty https://github.com/pulumi/esc/releases/tag/v0.11.0
As GitHub users receive an email with each GitHub release, it would be great to publish all the details when a a new release is out.
Especially since it seems to be published in https://github.com/pulumi/esc/blob/main/CHANGELOG.md

A great example would be https://github.com/pulumi/pulumi-azure-native/releases/tag/v2.68.0

### Example

n/a

### Output of `pulumi about`

n/a

### Additional context

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by seanyeh** [comment]
I was just looking into this yesterday! I'll assign myself to this

**Comment by seanyeh** [comment]
Previously we've been moving the changes out of CHANGELOG_PENDING in the release PR, but I think we should actually do this after the release PR (and after we push up the tags). This is because when we push up the new version tags, goreleaser reads CHANGELOG_PENDING for release notes to publish. @IaroslavTitov FYI we should do this in psp as well.

**Comment by IaroslavTitov** [comment]
> Previously we've been moving the changes out of CHANGELOG_PENDING in the release PR, but I think we should actually do this after the release PR (and after we push up the tags). This is because when we push up the new version tags, goreleaser reads CHANGELOG_PENDING for release notes to publish. [@IaroslavTitov](https://github.com/IaroslavTitov) FYI we should do this in psp as well.

This would changelog text on [this page](https://github.com/pulumi/pulumi-pulumiservice/releases)? Yeah, would be nice, we can take a look what's needed for that.
