### ISSUE TITLE
Add application-level SDKs for Python, JavaScript, Go, .NET and more

### ISSUE THREAD

**Issue by lukehoban** [pulumi/esc#60]
Pulumi ESC can already be accessed from application code via REST API and the CLI.  But there are many use cases where it is useful to consume configuration from Pulumi ESC directly from within application code.

We plan to do this by offering native SDKs for TypeScript, Python, Go and .NET.  

As part of designing these SDKs, we have a few goals:
1. The ability to authenticate to Pulumi ESC (initially using a Pulumi Access Token, int he future using additional application-level authentication methods)
2. The ability to open an environment to get back a set of configuration values.
3. The ability to `watch` an environment to get a callback invoked when that environment changes. 

Here's a conceptual sketch of what this might look like:

```ts
import * as esc from ‘pulumi-esc’;

const env = new esc.Environment(...);
const config = env.open("shopping-service-production");
env.watch("shopping-service-production", config => …);
```

**Comment by komalali** [comment]
A very WIP branch where I started playing with this idea: https://github.com/pulumi/esc/pull/219

Usage can be determined by examining the test file: https://github.com/pulumi/esc/pull/219/files#diff-c9d85370cddbf279425cc6431472496aaac8ac4bfc7aa067a4b1d6ed5034a8f7

Very much encourage folks that are motivated to try this out and let us hear your feedback!

**Comment by moos3** [comment]
would be awesome if you could also update a ESC from the application code.

**Comment by arunkumar611** [comment]
Docs for Typescript, go, Python SDK: https://www.pulumi.com/docs/esc/sdk/
