### ISSUE TITLE
Support version controlling environments

### ISSUE THREAD

**Issue by lukehoban** [pulumi/esc#63]
Today, environments are stored and versioning within Pulumi Cloud.  We know there are cases where users would like to be able to author and version their environments via source-controlled code files.  

There are two options we are exploring for this:
1. Enabling the Pulumi Cloud Pulumi Provider to define and manage the desired state of Environments via a Pulumi IaC program.  This would offer a way to write code (in Pulumi IaC) to manage the lifecycle of environments across an organization (and to detect and manage drift via `pulumi refresh`).
2. Providing a mode where environments are authored locally (in source controlled Git repo), and pushed up to Pulumi ESC as part of a "deployment" process of some sort directly.

We may ultimately want/need to provide both of these.
```[tasklist]
### Tasks
```

**Comment by joeduffy** [comment]
Am going to guess most users would expect/want something more like 2 (although tbh I expect most people to assume “code” is source of truth). It will be interesting to get feedback before deciding.

**Comment by komalali** [comment]
Related issue for 1 in pulumiservice provider repo: https://github.com/pulumi/pulumi-pulumiservice/issues/179

**Comment by grantjoy** [comment]
Any progress on this?

**Comment by komalali** [comment]
We've released ESC versioning! https://www.pulumi.com/blog/esc-versioning-launch/

**Comment by ekkohdev** [comment]
For anyone looking at this, https://github.com/pulumi/pulumi-pulumiservice/pull/271 is the change that added support for the `Environment` resource to the https://github.com/pulumi/pulumi-pulumiservice provider.

The link to ESC versioning does not really address the original issue. The changes above do, though.
