### ISSUE TITLE
Support for 1Password configuration provider

### ISSUE THREAD

**Issue by lukehoban** [pulumi/esc#64]
We've had many asks to support pulling credentials out of 1Password.  Doing this would enable 1Password to be the source of truth, but to pulll required values down on-demand, and authenticated at the time of access, instead of copy-pasting values out of 1Password into other configuration systems.

This is currently dependent on REST API/SDK for accessing 1Password data via an application token.

**Comment by gigo1980** [comment]
Hi @lukehoban, sounds good. Just inform me if you need beta testers.
I have used it before with Terraform to shift values to hashicorp vault. Also used 1Password as an external secrets provider in kubernetes. I think tohandle everything over pulumi esc sounds good. And to manage and share credentials over 1password with my team.

**Comment by cleverguy25** [comment]
@gigo1980 please send me an email at cleve@pulumi.com and I can get you added to the beta.
