### ISSUE TITLE
Support Pulumi IaC stack reference configuration provider

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/esc#90]
We've had several requests to support reading in a Pulumi IaC stack reference from within an environment. This would enable easily consuming infrastructure metadata (subnet IDs, IP addresses, DNS names, etc) from your Pulumi programs in a centrally managed way.

**Comment by LouisAmon** [comment]
That would be a killer feature for us : being able to generate a dotenv with all the configs, either from Pulumi, from secrets and static settings or from providers such as AWS 🔥

**Comment by lblackstone** [comment]
Support for this has merged in the Pulumi backend, and will be rolling out with docs in the next few days. Closing this as completed.
