### ISSUE TITLE
direnv support

### ISSUE THREAD

**Issue by t0yv0** [pulumi/esc#99]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Consider supporting [direnv](https://direnv.net/), a popular shell extension that loads an `.envrc` file to modify the default environment upon entering a given directory. There are also VSCode, Emacs and other extensions available to respect the `.envrc` files automatically for files and processes under a given folder.

How would esc support look like? There should be a way to reference esc in the .envrc files. Perhaps esc could simply export env variables in shell syntax.

**Comment by pgavlin** [comment]
https://www.pulumi.com/docs/esc/other-integrations/direnv/ documents how to integrate ESC with Direnv.
